version: '3.8'

services:
  pyaki:
    container_name: pyaki

    init: true
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - no_proxy="127.0.0.1,localhost"
      - NO_PROXY="127.0.0.1,localhost"
    volumes:
      - ..:/workspaces:cached
      - type: bind
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
