# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Integration (Python)
on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]  # Add more Python versions to test here

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Virtual Environment
      uses: actions/cache@v4
      with:
        path: |
          .venv
          ~/.cache/pip
          ~/.cache/pypoetry
        key: ${{ runner.os }}-venv-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev

    - name: Lint with ruff
      run: poetry run ruff check .
    - name: Check types with mypy
      run: poetry run mypy .
    - name: Test with pytest
      run: poetry run pytest .

    - name: Coveralls
      run: poetry run coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
